apiVersion: v1
kind: Pod
metadata:
  name: attendance-service
  namespace: default
  labels:
    app: attendance-service
spec:
  containers:
    - name: attendance-service
      image: "pusti/rso2324-team22-attendance-service:latest"
      ports:
        - containerPort: 80
          name:  http
      env:
        - name: POSTGRES_SERVER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres_server
        - name: POSTGRES_DATABASE
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres_attendance_database
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres_username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres_password
        - name: PlanningService__GraphQL__Url
          value: "$(PLANNING_SERVICE_SERVICE_HOST)/graphql"
        - name: PlanningService__GraphQL__Port
          value: "$(PLANNING_SERVICE_SERVICE_PORT)"
        - name: MembersService__GraphQL__Url
          value: "$(MEMBERS_SERVICE_SERVICE_HOST)/graphql"
        - name: MembersService__GraphQL__Port
          value: "$(MEMBERS_SERVICE_SERVICE_PORT)"
        - name: Kafka__Consumer__bootstrap__servers
          value: "$(KAFKA_SERVICE_HOST):$(KAFKA_SERVICE_PORT)"
      startupProbe:
        httpGet:
          path: /health/startup
          port: http
        initialDelaySeconds: 10
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /health/live
          port: http
        initialDelaySeconds: 10
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /health/ready
          port: http
        initialDelaySeconds: 20
        periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: attendance-service
spec:
  type: LoadBalancer
  selector:
    app: attendance-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
