apiVersion: v1
kind: Service
metadata:
  name: graylog
  namespace: default
spec:
  type: ExternalName
  externalName: graylog.monitoring.svc.cluster.local
  ports:
  - port: 12201
    protocol: TCP
    name: graylog-gelf-tcp
  - port: 12201
    protocol: UDP
    name: graylog-gelf-udp

