apiVersion: apps/v1
kind: Deployment
metadata:
  name: members-service
  namespace: default
  labels:
    app: members-service
spec:
  replicas: 5
  selector:
    matchLabels:
      app: members-service
  template:
    metadata:
      name: "members-service"
      namespace: default
      labels:
        app: members-service
    spec:
      containers:
        - name: members-service
          image: "pusti/rso2324-team22-members-service:latest"
          ports:
            - containerPort: 8080
              name:  http
          env:
            - name: CONNECTIONSTRINGS__MEMBERSDATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: members_service_connection_string
            - name: KAFKA_URL
              value: "$(KAFKA_SERVICE_HOST):$(KAFKA_SERVICE_PORT)"
            - name: SERILOG__WRITETO__0__ARGS__NAME
              value: "Graylog"
            - name: SERILOG__WRITETO__0__ARGS__HOSTNAMEORADDRESS
              value: "$(GRAYLOG_SERVICE_HOST)"
            - name: SERILOG__WRITETO__0__ARGS__PORT
              value: "$(GRAYLOG_SERVICE_PORT)"
            - name: SERILOG__WRITETO__0__ARGS__TRANSPORTTYPE
              value: "Udp"

---

apiVersion: v1
kind: Service
metadata:
  name: members-service
spec:
  type: ClusterIP
  selector:
    app: members-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
