apiVersion: apps/v1
kind: Deployment
metadata:
  name: members-service
  namespace: default
  labels:
    app: members-service
spec:
  replicas: 5
  selector:
    matchLabels:
      app: members-service
  template:
    metadata:
      name: "members-service"
      namespace: default
      labels:
        app: members-service
    spec:
      containers:
        - name: members-service
          image: "pusti/rso2324-team22-members-service:latest"
          ports:
            - containerPort: 8080
              name:  http
          env:
            - name: ConnectionStrings__MembersDatabase
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: members_service_connection_string
            - name: KAFKA_URL
              value: "http://$(KAFKA_SERVICE_HOST):$(KAFKA_SERVICE_PORT)"
            - name: SERILOG__WRITETO__ARGS_HOSTNAMEORADDRESS
              value: "$(GRAYLOG_SERVICE_HOST)"
            - name: SERILOG__WRITETO__ARGS_PORT
              value: "$(GRAYLOG_SERVICE_PORT)"
          # startupProbe:
          #   httpGet:
          #     path: /health/startup
          #     port: http
          #   initialDelaySeconds: 10
          #   periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: members-service
spec:
  type: LoadBalancer
  selector:
    app: members-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
