apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']
    
      - job_name: 'members-service'
        metrics_path: /metrics
        static_configs:
        - targets: ['members-service.default.svc.cluster.local']

      - job_name: 'planning-service'
        metrics_path: /metrics
        static_configs:
        - targets: ['planning-service.default.svc.cluster.local']

      - job_name: 'attendance-service'
        metrics_path: /metrics
        static_configs:
        - targets: ['attendance-service.default.svc.cluster.local']

      - job_name: 'webapp'
        metrics_path: /metrics
        static_configs:
        - targets: ['webapp.default.svc.cluster.local']

      - job_name: 'webapp-health'
        metrics_path: /healthmetrics
        static_configs:
        - targets: ['webapp.default.svc.cluster.local']

---

apiVersion: v1
kind: Pod
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
spec:
  containers:
    - name: prometheus
      image: prom/prometheus
      args:
        - "--storage.tsdb.retention.time=12h"
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus/"
        - "--web.enable-lifecycle"
        - "--web.route-prefix=/"
        - "--web.external-url=http://192.168.49.2/monitoring/prometheus"
      ports:
        - containerPort: 9090
          name: prometheus
      resources:
        requests:
          cpu: 500m
          memory: 500M
        limits:
          cpu: 1
          memory: 1Gi
      volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/
        - name: prometheus-storage-volume
          mountPath: /prometheus/
  volumes:
    - name: prometheus-config-volume
      configMap:
        defaultMode: 420
        name: prometheus-config

    - name: prometheus-storage-volume
      emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port_name: "prometheus"
spec:
    selector:
        app: prometheus
    type: NodePort
    ports:
    - port: 9090
      targetPort: prometheus
