apiVersion: v1
kind: Pod
metadata:
  name: graylog
  namespace: monitoring
  labels:
    app: graylog
spec:
  containers:
    - name: mongodb
      image: "mongo:7.0.5"
      ports:
        - containerPort: 27017
          protocol: TCP
          name: mongodb
      volumeMounts:
        - name: mongodb-data
          mountPath: /data/db

    - name: opensearch
      image: "opensearchproject/opensearch:2"
      env:
        - name: plugins.security.disabled
          value: "true"
        - name: discovery.type
          value: "single-node"
      volumeMounts:
        - name: opensearch-data
          mountPath: /usr/share/opensearch/data

    - name: graylog
      image: "graylog/graylog:5.2"
      env:
        - name: GRAYLOG_HTTP_BIND_ADDRESS
          value: "0.0.0.0:9000"
        - name: GRAYLOG_PASSWORD_SECRET
          valueFrom: 
            secretKeyRef: 
              name: graylog-secrets
              key: password_secret
        - name: GRAYLOG_ROOT_USERNAME
          valueFrom: 
            secretKeyRef: 
              name: graylog-secrets
              key: username
        - name: GRAYLOG_ROOT_PASSWORD_SHA2
          valueFrom: 
            secretKeyRef: 
              name: graylog-secrets
              key: password
        - name: GRAYLOG_HTTP_EXTERNAL_URI
          value: "http://192.168.49.2/monitoring/graylog/"
        - name: GRAYLOG_ELASTICSEARCH_HOSTS
          value: "http://localhost:9200"
        - name: GRAYLOG_MONGODB_URI
          value: "mongodb://localhost:27017/graylog"
      ports:
        - containerPort: 9000
          protocol: TCP
          name: graylog-rest
        - containerPort: 1514
          protocol: TCP
          name: syslog-tcp
        - containerPort: 1514
          protocol: UDP
          name: syslog-udp
        - containerPort: 12201
          protocol: TCP
          name: gelf-tcp
        - containerPort: 12201
          protocol: UDP
          name: gelf-udp

  volumes:
    - name: opensearch-data
      emptyDir: {}
    - name: mondogb-data
      emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: graylog
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: graylog
  ports:
    - name: graylog-rest
      protocol: TCP
      port: 9000
      targetPort: graylog-rest
    - name: syslog-tcp
      protocol: TCP
      port: 1514
      targetPort: syslog-tcp
    - name: syslog-udp
      protocol: UDP
      port: 1514
      targetPort: syslog-udp
    - name: gelf-tcp
      protocol: TCP
      port: 12201
      targetPort: gelf-tcp
    - name: gelf-udp
      protocol: UDP
      port: 12201
      targetPort: gelf-udp
