apiVersion: apps/v1
kind: Deployment
metadata:
  name: planning-service
  namespace: default
  labels:
    app: planning-service
spec:
  replicas: 5
  selector:
    matchLabels:
      app: planning-service
  template:
    metadata:
      name: planning-service
      namespace: default
      labels:
        app: planning-service
    spec:
      containers:
        - name: planning-service
          image: "pusti/rso2324-team22-planning-service:latest"
          ports:
            - containerPort: 8080
              name:  http
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
            - name: CONNECTIONSTRINGS__DATABASE
              value: "Database=planningservice; Host=$(POSTGRES_SERVICE_HOST); Port=$(POSTGRES_SERVICE_PORT); Username=postgres; Password=$(POSTGRES_PASSWORD);"
            - name: KAFKA_URL
              value: "$(KAFKA_SERVICE_HOST):$(KAFKA_SERVICE_PORT)"
            - name: SERILOG__WRITETO__0__ARGS__NAME
              value: "Graylog"
            - name: SERILOG__WRITETO__0__ARGS__HOSTNAMEORADDRESS
              value: "graylog.monitoring.svc.cluster.local"
            - name: SERILOG__WRITETO__0__ARGS__PORT
              value: "12201"
            - name: SERILOG__WRITETO__0__ARGS__TRANSPORTTYPE
              value: "Udp"

---

apiVersion: v1
kind: Service
metadata:
  name: planning-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/health_path: "/healthmetrics"
    prometheus.io/port_name: "http"
spec:
  type: ClusterIP
  selector:
    app: planning-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
