apiVersion: v1
kind: Pod
metadata:
  name: postgres
  namespace: default
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: "postgres:16.1"
      ports:
        - containerPort: 5432
          name: postgres
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: password
      volumeMounts:
        - name: postgres-data 
          mountPath: /var/lib/postgresql/data

  volumes:
    - name: postgres-data
      emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: postgres
