apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-service
  labels:
    app: resource-service
spec:
  replicas: 5
  selector:
    matchLabels:
      app: resource-service
  template:
    metadata:
      name: resource-service
      namespace: default
      labels:
        app: resource-service
    spec:
      containers:
        - name: resource-service
          image: "pusti/rso2324-team22-resource-service:latest"
          ports:
            - containerPort: 8080
              name:  http
          env:
            - name: POSTGRES_SERVER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_server
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_resource_database
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgres_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgres_password
            - name: PlanningService__GraphQL__Url
              value: "$(PLANNING_SERVICE_SERVICE_HOST)/graphql"
            - name: PlanningService__GraphQL__Port
              value: "$(PLANNING_SERVICE_SERVICE_PORT)"
            - name: MembersService__GraphQL__Url
              value: "$(MEMBERS_SERVICE_SERVICE_HOST)/graphql"
            - name: MembersService__GraphQL__Port
              value: "$(MEMBERS_SERVICE_SERVICE_PORT)"
          # startupProbe:
          #   httpGet:
          #     path: /health/startup
          #     port: http
          #   initialDelaySeconds: 10
          #   periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: resource-service
spec:
  type: ClusterIP
  selector:
    app: resource-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
